"""DevSRS — SRS-driven application builder.

Consumes a drafted SRS document (IEEE 830-style markdown produced by the
pipeline's SRSGenerator stage) and materializes it into a real, runnable
application scaffold:

  * ``cli`` — a Python CLI application with an argparse entry point
  * ``web`` — a full-stack FastAPI application with a static single-page UI
  * ``mcp`` — a Model Context Protocol (MCP) server exposing the app's core
    capabilities as tools over stdio JSON-RPC

Every generated app embeds a lightweight multi-agent orchestration layer
(``agents.py``) modeled on LangChain agent runtimes and AutoGen conversational
agents, so the resulting application is agent-powered regardless of target.

Two build modes:

  * **Template mode** (default, offline): deterministic, runnable code is
    generated locally from the parsed SRS blueprint. Works without any API key.
  * **LLM mode** (``use_llm=True`` + a real provider): the configured LLM
    writes the ``core.py`` implementation guided by the SRS; the scaffolding
    shell always comes from the templates.

Usage::

    from collabuild.devsrs import DevSRS

    builder = DevSRS(target="web", output_dir="generated_app")
    result = builder.build(srs_text)

CLI: ``collabuild devsrs --srs-file SRS.md --target web --output ./app``
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from string import Template

log = logging.getLogger("devsrs")

SUPPORTED_TARGETS = ("cli", "web", "mcp")

PACKAGE_README = Template("""# $TITLE

$DESCRIPTION

## Quick Start

$QUICKSTART

## Generated by DevSRS

This project was scaffolded by **DevSRS** from a drafted Software Requirements
Specification. The app ships with a LangChain/AutoGen-style multi-agent layer
(`agents.py`) and a core capability registry (`core.py`).

### Layout

$FILE_TREE

## SRS

The driving requirements document is `SRS.md` (IEEE 830 style).

## License

MIT
""")

AGENTS_PY = Template("""\"\"\"
$TITLE — multi-agent orchestration layer.

Modeled on LangChain agent runtimes and AutoGen conversational agents:
  - Tool  ~ LangChain tool / AutoGen function-tool
  - Agent ~ LangChain AgentExecutor loop / AutoGen ConversableAgent
  - Task  ~ a unit of work with a description and a result
  - Crew  ~ LangChain crew / AutoGen GroupChat manager

Agents share one protocol, so they can be driven from the CLI, the web API,
or the MCP server interchangeably.
\"\"\"

from __future__ import annotations

import logging
from dataclasses import dataclass, field

log = logging.getLogger(__name__)


class Tool:
    \"\"\"A single callable capability an agent can use.\"\"\"

    def __init__(self, name: str, description: str, fn):
        self.name = name
        self.description = description
        self.fn = fn

    def run(self, *args, **kwargs):
        return self.fn(*args, **kwargs)


@dataclass
class Task:
    \"\"\"A unit of work handed to an agent.\"\"\"

    description: str
    result: str = ""
    metadata: dict = field(default_factory=dict)


class Agent:
    \"\"\"A role-based agent that executes tasks with tools.

    Mirrors LangChain's reason->act->observe loop and AutoGen's
    ConversableAgent. The ``think`` callable can be any function -- an LLM,
    a rule engine, or a stub -- so the same agent works online and offline.
    \"\"\"

    def __init__(self, name: str, role: str, think=None, tools: list | None = None):
        self.name = name
        self.role = role
        self.think = think or self._default_think
        self.tools: dict[str, Tool] = {t.name: t for t in (tools or [])}
        self.memory: list[str] = []

    def _default_think(self, task: Task, context: str) -> str:
        \"\"\"Fallback brain: deterministic tool dispatch with error tolerance.\"\"\"
        for tool in self.tools.values():
            try:
                out = tool.run(task.description, context)
                if out is not None and str(out).strip():
                    return str(out)
            except Exception as exc:  # noqa: BLE001
                log.warning("[%s] tool %s failed: %s", self.name, tool.name, exc)
        return f"[{self.name}:{self.role}] processed: {task.description}"

    def execute(self, task: Task, context: str = "") -> str:
        log.info("[%s] executing task: %s", self.name, task.description)
        result = self.think(task, context)
        self.memory.append(result)
        task.result = result
        return result


class Crew:
    \"\"\"Sequential orchestration of agents (LangChain crew / AutoGen group chat).\"\"\"

    def __init__(self, agents: list | None = None):
        self.agents = agents or []

    def kickoff(self, task: Task, context: str = "") -> list[str]:
        ctx = context
        results: list[str] = []
        for agent in self.agents:
            result = agent.execute(task, ctx)
            results.append(result)
            ctx = result
        return results
""")

CORE_PY = Template("""\"\"\"
$TITLE — core domain layer.

Implements the capabilities extracted from the SRS:
$FEATURES

Front-ends (CLI / API / MCP) and agents dispatch to :func:`run_capability`.
\"\"\"

from __future__ import annotations

import logging
from typing import Any, Callable

log = logging.getLogger(__name__)


def _default_impl(name: str) -> Callable[[dict[str, Any] | None], dict[str, Any]]:
    \"\"\"Deterministic placeholder implementation for a required capability.\"\"\"

    def impl(args: dict[str, Any] | None = None) -> dict[str, Any]:
        args = args or {}
        log.info("running capability: %s args=%s", name, args)
        return {
            "ok": True,
            "feature": name,
            "input": args,
            "result": f"[{name}] executed",
        }

    return impl


CORE: dict[str, Callable[[dict[str, Any] | None], dict[str, Any]]] = {
$CORE_ENTRIES}


def run_capability(name: str, args: dict[str, Any] | None = None) -> dict[str, Any]:
    \"\"\"Run a capability by name. Unknown names raise ValueError.\"\"\"
    if name not in CORE:
        raise ValueError(
            f"unknown capability: {name} (available: {', '.join(sorted(CORE))})"
        )
    return CORE[name](args)


def capabilities() -> list[str]:
    return sorted(CORE)
""")

CLI_MAIN = Template("""\"\"\"
$TITLE — command line interface.

Generated by DevSRS from a drafted SRS. Run any capability through the
agent layer or directly:

    python main.py --list
    python main.py $FIRST_CAP --args '{"key": "value"}'
    python main.py $FIRST_CAP --agent planner
\"\"\"

from __future__ import annotations

import argparse
import json
import sys

import agents
import core


def build_parser() -> argparse.ArgumentParser:
    caps = core.capabilities()
    parser = argparse.ArgumentParser(prog="$PACKAGE", description="$DESCRIPTION")
    parser.add_argument("capability", nargs="?", help="capability to run: " + ", ".join(caps))
    parser.add_argument("--args", default="{}", help='JSON args, e.g. {"path": "x.pdf"}')
    parser.add_argument("--list", action="store_true", help="list available capabilities")
    parser.add_argument("--agent", default="", help="route through a named agent (see agents.py)")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.list:
        print("Capabilities:")
        for cap in core.capabilities():
            print(f"  - {cap}")
        return 0

    if not args.capability:
        parser.print_help()
        return 1

    try:
        payload = json.loads(args.args)
    except json.JSONDecodeError:
        print(f"error: --args must be valid JSON, got: {args.args!r}", file=sys.stderr)
        return 2

    if args.agent:
        tools = [agents.Tool(cap, cap, lambda _c=cap, _p=payload: core.run_capability(_c, _p))
                 for cap in core.capabilities()]
        agent = agents.Agent(name=args.agent, role=args.agent, tools=tools)
        task = agents.Task(description=args.capability)
        result = agent.execute(task, json.dumps(payload))
    else:
        result = core.run_capability(args.capability, payload)

    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
""")

WEB_MAIN = Template("""\"\"\"
$TITLE — FastAPI application.

Generated by DevSRS from a drafted SRS. Serves a static single-page UI and a
REST API backed by the core capability registry and the agent crew.

    pip install -r requirements.txt
    uvicorn main:app --reload
\"\"\"

from __future__ import annotations

import json
from pathlib import Path

import agents
import core
from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles

STATIC = Path(__file__).parent / "static"

app = FastAPI(title="$TITLE", version="1.0.0")

CREW = agents.Crew([
    agents.Agent(
        "planner",
        "routes requests through capabilities",
        tools=[agents.Tool(cap, cap, lambda _c=cap, **kw: core.run_capability(_c, kw.get("args")))
               for cap in core.capabilities()],
    ),
])


@app.get("/", response_class=HTMLResponse)
async def index() -> str:
    return (STATIC / "index.html").read_text(encoding="utf-8")


@app.get("/api/health")
async def health() -> dict:
    return {"ok": True}


@app.get("/api/capabilities")
async def capabilities() -> dict:
    return {"capabilities": core.capabilities()}


@app.post("/api/run/{capability}")
async def run(capability: str, payload: dict | None = None) -> dict:
    payload = payload or {}
    if capability not in core.capabilities():
        raise HTTPException(404, f"unknown capability: {capability}")
    try:
        return core.run_capability(capability, payload)
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(500, str(exc))


@app.post("/api/agents/kickoff")
async def kickoff(payload: dict) -> dict:
    task = agents.Task(description=str(payload.get("task", "")))
    context = json.dumps(payload.get("context", ""))
    return {"results": CREW.kickoff(task, context)}


app.mount("/static", StaticFiles(directory=str(STATIC)), name="static")
""")

WEB_INDEX = Template("""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$TITLE</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 720px; margin: 3rem auto; padding: 0 1rem; color: #222; }
  code, pre { background: #f4f4f4; padding: .2rem .4rem; border-radius: 4px; }
  pre { padding: 1rem; overflow: auto; }
  input, select, button { font-size: 1rem; padding: .5rem; margin: .25rem 0; }
  .row { display: flex; gap: .5rem; margin-bottom: 1rem; }
  .cap { background: #eef; padding: .5rem 1rem; border-radius: 6px; margin: .25rem; cursor: pointer; border: 1px solid #cce; }
  .cap:hover { background: #dde; }
  #out { white-space: pre-wrap; }
</style>
</head>
<body>
<h1>$TITLE</h1>
<p>$DESCRIPTION</p>
<div class="row">
  <select id="cap"></select>
  <input id="args" placeholder='{"key": "value"}' value="{}">
  <button onclick="run()">Run</button>
</div>
<h2>Capabilities</h2>
<div id="caps"></div>
<h2>Output</h2>
<pre id="out"></pre>
<script>
const qs = (id) => document.getElementById(id);

async function loadCaps() {
  const res = await fetch("/api/capabilities");
  const data = await res.json();
  qs("cap").innerHTML = data.capabilities.map(c => "<option>" + c + "</option>").join("");
  qs("caps").innerHTML = data.capabilities.map(c => "<span class=cap>" + c + "</span>").join("");
}

async function run() {
  const cap = qs("cap").value;
  let args = {};
  try { args = JSON.parse(qs("args").value || "{}"); } catch { qs("out").textContent = "invalid JSON args"; return; }
  const res = await fetch("/api/run/" + cap, { method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify(args) });
  qs("out").textContent = JSON.stringify(await res.json(), null, 2);
}

loadCaps();
</script>
</body>
</html>
""")

MCP_SERVER = Template("""\"\"\"
$TITLE — Model Context Protocol (MCP) server.

Exposes the app's core capabilities as MCP tools over stdio JSON-RPC
(protocol subset: initialize, tools/list, tools/call). Connect from any MCP
client (Claude Desktop, Cursor, mcp CLI):

    mcp install server.py
    python server.py
\"\"\"

from __future__ import annotations

import json
import logging
import sys

import core

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger("mcp")

SERVER_NAME = "$PACKAGE"
VERSION = "1.0.0"

TOOLS = [
$MCP_TOOLS]


def _read_message() -> dict | None:
    line = sys.stdin.readline()
    if not line:
        return None
    try:
        return json.loads(line)
    except json.JSONDecodeError as exc:
        log.warning("invalid JSON-RPC frame: %s", exc)
        return None


def _write_message(msg: dict) -> None:
    sys.stdout.write(json.dumps(msg) + "\\n")
    sys.stdout.flush()


def _error(rid, code: int, message: str) -> dict:
    return {"jsonrpc": "2.0", "id": rid, "error": {"code": code, "message": message}}


def handle_request(req: dict) -> dict:
    rid = req.get("id")
    method = req.get("method", "")
    params = req.get("params") or {}

    if method == "initialize":
        return {
            "jsonrpc": "2.0",
            "id": rid,
            "result": {
                "protocolVersion": params.get("protocolVersion", "2024-11-05"),
                "capabilities": {"tools": {}},
                "serverInfo": {"name": SERVER_NAME, "version": VERSION},
            },
        }

    if method == "tools/list":
        return {"jsonrpc": "2.0", "id": rid, "result": {"tools": TOOLS}}

    if method == "tools/call":
        name = params.get("name", "")
        args = params.get("arguments") or {}
        for tool in TOOLS:
            if tool["name"] == name:
                output = core.run_capability(name, args)
                text = json.dumps(output, ensure_ascii=False)
                return {
                    "jsonrpc": "2.0",
                    "id": rid,
                    "result": {"content": [{"type": "text", "text": text}]},
                }
        return _error(rid, -32602, f"unknown tool: {name}")

    if method == "notifications/initialized":
        return {"jsonrpc": "2.0", "id": rid, "result": {}}

    return _error(rid, -32601, f"method not found: {method}")


def serve() -> int:
    log.info("%s MCP server ready", SERVER_NAME)
    while True:
        req = _read_message()
        if req is None:
            break
        try:
            response = handle_request(req)
        except Exception as exc:  # noqa: BLE001
            log.exception("request failed")
            response = _error(req.get("id"), -32603, str(exc))
        if response is not None:
            _write_message(response)
    return 0


if __name__ == "__main__":
    sys.exit(serve())
""")

MCP_TEST = Template("""\"\"\"Basic MCP server test: initialize, tools/list, tools/call over stdio.\"\"\"

import json
import subprocess
import sys

SERVER = sys.argv[1] if len(sys.argv) > 1 else "server.py"


def send(proc, payload: dict) -> dict:
    proc.stdin.write(json.dumps(payload) + "\\n")
    proc.stdin.flush()
    line = proc.stdout.readline()
    return json.loads(line)


def test_mcp_flow() -> None:
    proc = subprocess.Popen(
        [sys.executable, SERVER],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    try:
        init = send(proc, {"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {}})
        assert init["result"]["serverInfo"]["name"] == "$PACKAGE", init

        listing = send(proc, {"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}})
        tools = [t["name"] for t in listing["result"]["tools"]]
        assert len(tools) >= 1, listing

        call = send(proc, {
            "jsonrpc": "2.0", "id": 3, "method": "tools/call",
            "params": {"name": tools[0], "arguments": {}},
        })
        assert call["result"]["content"], call
        print("MCP flow OK:", tools[0])
    finally:
        proc.kill()


if __name__ == "__main__":
    test_mcp_flow()
""")

CORE_TEST = Template("""\"\"\"Smoke tests for the core capability registry.\"\"\"

import core


def test_capabilities_nonempty() -> None:
    assert len(core.capabilities()) >= 1


def test_run_known_capability() -> None:
    cap = core.capabilities()[0]
    result = core.run_capability(cap, {})
    assert result["ok"] is True
    assert result["feature"] == cap


def test_run_unknown_capability() -> None:
    import pytest

    with pytest.raises(ValueError):
        core.run_capability("does_not_exist")
""")

REQUIREMENTS = {
    "cli": "# stdlib only — no external dependencies required\n",
    "web": "fastapi>=0.110\nuvicorn[standard]>=0.29\n",
    "mcp": "# stdlib only — MCP runs over stdio JSON-RPC\n",
}

ENV_EXAMPLE = Template("""# $PACKAGE — environment configuration
LOG_LEVEL=INFO
""")

DOCKERFILE = Template("""FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
""")


@dataclass
class SRSBlueprint:
    """Structured requirements extracted from a drafted SRS document."""

    title: str = "Generated Application"
    description: str = ""
    actors: list[str] = field(default_factory=list)
    functional_requirements: list[str] = field(default_factory=list)
    nonfunctional_requirements: list[str] = field(default_factory=list)
    modules: list[str] = field(default_factory=list)
    features: list[str] = field(default_factory=list)
    tech_stack: list[str] = field(default_factory=list)
    api_endpoints: list[str] = field(default_factory=list)


# ── SRS parsing ──────────────────────────────────────────────────────────────

_SECTION_RE = re.compile(r"^\s*(#{1,6}\s+|(?:FR|NF)\s*-?\s*\d+|[-*]\s+)")


def _slugify(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return slug or "capability"


def _section_lines(text: str, *titles: str) -> list[str]:
    """Return stripped lines under the first markdown heading matching any title."""
    capture = False
    out: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            if capture:
                break
            capture = any(t.lower() in line.lower() for t in titles)
            continue
        if capture:
            out.append(line)
    return out


def _bullets(lines: list[str]) -> list[str]:
    items = []
    for line in lines:
        m = re.match(r"^\s*[-*]\s+(.+)$", line)
        if m:
            items.append(m.group(1).strip())
    return items


def _numbered(lines: list[str], pattern: str) -> list[str]:
    found = []
    for line in lines:
        if re.search(pattern, line, re.I):
            cleaned = re.sub(r"^[-*\d.\s:]+", "", line).strip()
            if cleaned and cleaned not in found:
                found.append(cleaned)
    return found


def parse_srs(text: str) -> SRSBlueprint:
    """Parse an IEEE 830-style SRS markdown document into a SRSBlueprint."""
    bp = SRSBlueprint()

    m = re.search(r"^\s*#\s+(.+)$", text, re.M)
    if m:
        bp.title = m.group(1).strip()
    m = re.search(r"Purpose[:\-]\s*(.+)", text, re.I)
    if m:
        bp.description = m.group(1).strip()

    bp.functional_requirements = _numbered(
        text.splitlines(), r"^\s*(?:- )?FR\s*-?\s*\d+"
    )
    bp.nonfunctional_requirements = _numbered(
        text.splitlines(), r"^\s*(?:- )?NF\s*-?\s*\d+"
    )

    bp.features = _bullets(_section_lines(text, "system features", "features", "modules"))
    bp.tech_stack = _bullets(
        _section_lines(text, "technology", "tech stack", "external interfaces")
    )

    for line in text.splitlines():
        if re.search(r"(GET|POST|PUT|DELETE|PATCH)\s+/", line, re.I):
            ep = re.sub(r"^[-*\s]+", "", line).strip()
            if ep not in bp.api_endpoints:
                bp.api_endpoints.append(ep)

    for line in _bullets(_section_lines(text, "user characteristics", "actors")):
        bp.actors.append(line)

    names = bp.features or bp.modules or bp.functional_requirements or ["process"]
    bp.modules = [n for n in names if not n.lower().startswith(("fr-", "nf-"))]
    bp.features = bp.features or bp.modules

    if not bp.description:
        bp.description = f"A system built from the SRS for {bp.title}."

    return bp


# ── Template assembly ────────────────────────────────────────────────────────

def _core_entries(blueprint: SRSBlueprint) -> str:
    names = blueprint.features or ["process"]
    lines = []
    for name in names:
        lines.append(f'    "{_slugify(name)}": _default_impl("{name}"),')
    return "\n".join(lines)


def _mcp_tools(blueprint: SRSBlueprint) -> str:
    names = blueprint.features or ["process"]
    tools = []
    for name in names[:25]:
        slug = _slugify(name)
        tools.append(
            f'        {{"name": "{slug}", "description": "{name}", '
            f'"inputSchema": {{"type": "object", "properties": {{}}, "additionalProperties": True}}}},'
        )
    return "\n".join(tools)


def _file_tree(paths: list[str]) -> str:
    return "\n".join(f"├── {p}" for p in paths)


def _ctx(blueprint: SRSBlueprint, package: str, target: str, paths: list[str],
         quickstart: str) -> dict:
    caps = [str(_slugify(n)) for n in (blueprint.features or ["process"])]
    return {
        "TITLE": blueprint.title,
        "PACKAGE": package,
        "DESCRIPTION": blueprint.description,
        "FEATURES": "\n".join(f"- {n}" for n in (blueprint.features or ["process"])),
        "CORE_ENTRIES": _core_entries(blueprint),
        "MCP_TOOLS": _mcp_tools(blueprint),
        "FIRST_CAP": caps[0] if caps else "process",
        "QUICKSTART": quickstart,
        "FILE_TREE": _file_tree(paths),
    }


def files_for(blueprint: SRSBlueprint, target: str) -> dict[str, str]:
    """Return {relative_path: content} for a fully runnable scaffold."""
    if target not in SUPPORTED_TARGETS:
        raise ValueError(f"unsupported target {target!r}; expected one of {SUPPORTED_TARGETS}")

    package = _slugify(blueprint.title) or "generated_app"
    if target == "cli":
        files = {
            "core.py": CORE_PY,
            "agents.py": AGENTS_PY,
            "main.py": CLI_MAIN,
            "tests/test_core.py": CORE_TEST,
            "requirements.txt": REQUIREMENTS["cli"],
            ".env.example": ENV_EXAMPLE,
            "README.md": PACKAGE_README,
        }
        quickstart = "python main.py --list"
    elif target == "web":
        files = {
            "main.py": WEB_MAIN,
            "core.py": CORE_PY,
            "agents.py": AGENTS_PY,
            "static/index.html": WEB_INDEX,
            "tests/test_core.py": CORE_TEST,
            "Dockerfile": DOCKERFILE,
            "requirements.txt": REQUIREMENTS["web"],
            ".env.example": ENV_EXAMPLE,
            "README.md": PACKAGE_README,
        }
        quickstart = "pip install -r requirements.txt && uvicorn main:app --reload"
    else:  # mcp
        files = {
            "server.py": MCP_SERVER,
            "core.py": CORE_PY,
            "agents.py": AGENTS_PY,
            "tests/test_core.py": CORE_TEST,
            "tests/test_mcp.py": MCP_TEST,
            "requirements.txt": REQUIREMENTS["mcp"],
            ".env.example": ENV_EXAMPLE,
            "README.md": PACKAGE_README,
        }
        quickstart = "python server.py"

    ctx = _ctx(blueprint, package, target, list(files), quickstart)
    rendered = {
        rel: (tmpl.substitute(ctx) if isinstance(tmpl, Template) else tmpl)
        for rel, tmpl in files.items()
    }
    rendered["README.md"] += "\nGenerated by Collabuild DevSRS.\n"
    return rendered


# ── Builder ──────────────────────────────────────────────────────────────────

class DevSRS:
    """Build a runnable application from a drafted SRS document."""

    def __init__(self, provider=None, target: str = "cli", model: str = "",
                 output_dir: str = "generated_app", max_tokens: int = 4096):
        if target not in SUPPORTED_TARGETS:
            raise ValueError(f"unsupported target {target!r}; expected one of {SUPPORTED_TARGETS}")
        self.provider = provider
        self.target = target
        self.model = model
        self.output_dir = Path(output_dir)
        self.max_tokens = max_tokens

    def _llm_available(self) -> bool:
        if self.provider is None:
            return False
        try:
            from .providers import DevProvider
            return not isinstance(self.provider, DevProvider)
        except ImportError:
            return True

    def _generate_core_with_llm(self, blueprint: SRSBlueprint) -> str:
        """Ask the LLM to write the core.py implementation from the SRS."""
        sys_prompt = (
            "You are an expert application developer. Write production-grade "
            "stdlib-only Python from a software requirements specification."
        )
        reqs = "\n".join(f"- {r}" for r in blueprint.functional_requirements[:15])
        features = "\n".join(f"- {n}" for n in blueprint.features[:15])
        user_prompt = (
            f"Write the complete implementation of `core.py` for this system.\n\n"
            f"Title: {blueprint.title}\n"
            f"Features/modules:\n{features}\n"
            f"Functional requirements:\n{reqs}\n\n"
            f"Requirements:\n"
            f"- Provide `CORE` dict mapping capability name -> callable(args: dict|None) -> dict\n"
            f"- Provide `run_capability(name, args)` and `capabilities()` functions\n"
            f"- stdlib only, no external imports\n"
            f"- Return ONLY the python code in a ```python fenced block."
        )
        resp = self.provider.chat(
            self.model,
            messages=[
                {"role": "system", "content": sys_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.2,
            max_tokens=self.max_tokens,
        )
        m = re.search(r"```python\s*\n(.*?)```", resp, re.DOTALL)
        code = m.group(1).strip() if m else resp.strip()
        if code.startswith("Error:"):
            return ""
        return code

    def _smoke_test(self, files: dict[str, str]) -> list[dict]:
        """Syntax-check every generated .py file (no execution)."""
        import py_compile

        results = []
        for rel in files:
            if not rel.endswith(".py"):
                continue
            path = self.output_dir / rel
            try:
                py_compile.compile(str(path), doraise=True)
                results.append({"file": rel, "ok": True})
            except Exception as exc:  # noqa: BLE001
                results.append({"file": rel, "ok": False, "error": str(exc)})
        return results

    def build(self, srs_text: str, use_llm: bool = True) -> dict:
        """Build the application. Returns a structured result dict."""
        blueprint = parse_srs(srs_text)
        files = files_for(blueprint, self.target)

        if use_llm and self._llm_available():
            try:
                code = self._generate_core_with_llm(blueprint)
                if code:
                    files["core.py"] = code
            except Exception as exc:  # noqa: BLE001
                log.warning("LLM codegen failed, using template: %s", exc)

        self.output_dir.mkdir(parents=True, exist_ok=True)
        written = []
        for rel, content in files.items():
            path = self.output_dir / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            written.append(rel)

        smoke = self._smoke_test(files)

        return {
            "target": self.target,
            "output_dir": str(self.output_dir),
            "files": written,
            "smoke_test": smoke,
            "smoke_ok": all(r["ok"] for r in smoke),
            "blueprint": {
                "title": blueprint.title,
                "description": blueprint.description,
                "actors": blueprint.actors,
                "features": blueprint.features,
                "functional_requirements": blueprint.functional_requirements,
                "nonfunctional_requirements": blueprint.nonfunctional_requirements,
                "tech_stack": blueprint.tech_stack,
                "api_endpoints": blueprint.api_endpoints,
            },
        }
